[tool.bumpversion]
current_version = "2.0.0"

[[tool.bumpversion.files]]
filename = "README.md"
search = 'conjikidow/bump-version@v{current_version}'
replace = 'conjikidow/bump-version@v{new_version}'
